FROM python:2.7
MAINTAINER eums <eums@thoughtworks.com>

ENV PYTHONUNBUFFERED 1

RUN export DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y supervisor

# Add unpriviledged worker user
RUN adduser --disabled-password --gecos '' worker

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY scripts/packaging/eums.uwsgi.ini /etc/uwsgi/sites/eums.uwsgi.ini
COPY scripts/deployment/celery.sh /celery.sh
COPY scripts/supervisor/celeryd.conf /etc/supervisor/conf.d/celery.conf

RUN mkdir -p /eums/client
WORKDIR /eums/client/

RUN mkdir /fixtures
COPY ./client/test/functional/fixtures/ /fixtures/

COPY ./build/ /eums/
VOLUME ./build/:/eums/

WORKDIR /eums/
EXPOSE 8000

# RUN python build/manage.py syncdb --noinput
# RUN python manage.py migrate
# RUN python manage.py setup_permissions
# RUN python manage.py shell_plus < eums/fixtures/load_flows_and_questions.py

CMD /usr/local/bin/uwsgi --emperor /etc/uwsgi/sites --env DJANGO_SETTINGS_MODULE=eums.staging_settings
