FROM python:2.7
MAINTAINER eums <eums@thoughtworks.com>

ENV PYTHONUNBUFFERED 1

RUN export DEBIAN_FRONTEND=noninteractive

# nodejs-legacy deals with npm packages looking for a `node` binary
RUN apt-get update && apt-get install -y npm nodejs nodejs-legacy
RUN npm install -g bower grunt grunt-cli

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir -p /eums/client
WORKDIR /eums/client

COPY client/package.json client/bower.json /eums/client/

RUN npm install
RUN bower install --allow-root

ADD . /eums
VOLUME .:/eums

EXPOSE 80

WORKDIR /eums/client
RUN grunt package

WORKDIR /eums

CMD sleep 4 && python build/manage.py migrate && python build/manage.py runserver 0.0.0.0:80
