FROM python:2.7
MAINTAINER eums <eums@thoughtworks.com>

ENV PYTHONUNBUFFERED 1

RUN export DEBIAN_FRONTEND=noninteractive

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD python
