FROM python:2.7
MAINTAINER eums <eums@thoughtworks.com>

ENV PYTHONUNBUFFERED 1
RUN export DEBIAN_FRONTEND=noninteractive

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /opt/app/eums
COPY ./build/ /opt/app/eums
# VOLUME .:/eums

EXPOSE 80

WORKDIR /opt/app/eums

CMD sleep 4 && python manage.py runserver 0.0.0.0:80
